sonar.projectKey=MuhammadTouqeerAhmad_cohort-9-mern-9816-muhammad
sonar.organization=muhammadtouqeerahmad

sonar.sources=Backend,Frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.sourceEncoding=UTF-8