name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f599
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}